### ISSUE TITLE
a lot of bugs and disorder code implemented

### ISSUE THREAD

**Issue by MatiasWebDevCoder4517** [shubham1710/ByteWalk#12]
- django_gcloud_storage NOT FOUND,
- A LOT OF endif , endfor, endblock attachments are incorrectly implemented, 
- app installing methods like 'users.apps.UsersConfig' are almost obsolete. Is a better practice to implement like this 'apps.users', this protects the system from unexpected errors around the apps. 
- Don't upload to heroku if the project have errors. Better practice to finish a functional or working local proyect, the typical "finish-proyect before deployment". This concepts explains better to the beginner practitioners. 
-

**Comment by shubham1710** [comment]
Thank you for pointing out the errors. 

1) django_gcloud_storage is a library and needs to be installed first before using it. 
https://pypi.org/project/django-gcloud-storage/

2) As far as I know, those statements were correctly implemented since project was working and running fine on Heroku. I have thoroughly tested it. But I will once again check those.

3) Yes, these needs updating. Actually when I was learning, I learnt it that way so implemented it in that particular way. Would need to update them to the new version.

4) Actually, the project was working fine and it was live on Heroku. In fact, it had 100+ users who made accounts and posted images or commented on the website. So, it worked fine at that moment. Then my GCloud free trial expired and I had to take it down.
